### PR TITLE
[MDEP-716] - TestListClassesMojo logs too much

### PR DESCRIPTION
**Pull request by raupachz**
Hello there,

attached is a PR for [MDEP-716](https://issues.apache.org/jira/browse/MDEP-716). This is an `up-for-grabs` issue. 

This code uses Mockito and creates a mock of the `org.apache.maven.plugin.logging.Log.java`. A redirect of `System.out` is not needed. This has also the nice benefit of argument matching. 

---

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MDEP) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MDEP-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MDEP-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Review by slawekjaranowski — COMMENTED** [review]
Are files different?
 src/test/resources/unit/list-test/testListClassesNotTransitive.txt
 src/test/resources/unit/list-test/testListClassesTransitive.txt

If yes we have the same output for different inputs for `transitive`...

**Comment by raupachz** [comment]
Hi @slawekjaranowski 

no, the files are the same. I did not check the output. Before the output was just written to `System.out` without any checking. I treated every unit-test as a separate unit with an individual input file. Made sense to me. Even if this results in duplicate file content.

If `org.apache.commons:commons-lang3:3.6` has no transitive dependencies then the output should be the same - to my understanding.

**Comment by slawekjaranowski** [comment]
> If `org.apache.commons:commons-lang3:3.6` has no transitive dependencies then the output should be the same - to my understanding.

good understanding, 

So I see some improvement here
 - test for artifacts without transitive dependencies - as we have now, only test name / description should point such case
- test for artifact with transitive dependencies

of course it is job for next PR

**Comment by jira-importer** [comment]
Resolve #1209

**Pull request merged**
