### PR TITLE
use Apache Commons StringUtil

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by elharo** [comment]
Failure might be flaky or perhaps platform dependent?

[INFO] -------------------------------------------------
Error:  The following builds failed:
Error:  *  analyze-testDependencyWithNonTestScope/pom.xml
[INFO] -------------------------------------------------

**Comment by elharo** [comment]
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project nonTestScopeTestArtifactsAnalysis: Fatal error compiling: error: release version 1.7 not supported -> [Help 1]

**Comment by elharo** [comment]
It does look like the failing CI is broken at head base don other failing PRs

**Review by michael-o — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
Maybe it is technically easy change .... but we should report issue for such, and each project should have own issue
Now I see a mess like in #299 - which is connected with issue from MNG

**Comment by jira-importer** [comment]
Resolve #1353

**Pull request merged**
