### PR TITLE
JDK 20 to 21

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by elharo** [comment]
Looks like this plugin does have a JDK 21 issue:

 Caused by: org.apache.maven.plugin.PluginContainerException: An API incompatibility was encountered while executing com.diffplug.spotless:spotless-maven-plugin:2.37.0:check: java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree com.sun.tools.javac.tree.JCTree$JCImport.getQualifiedIdentifier()'

**Comment by elharo** [comment]
Or rather spotless does

**Comment by slachiewicz** [comment]
Never version of the spotless plugin requires Java 11

**Comment by slawekjaranowski** [comment]
suppressed by #368

**Pull request closed without merging**
