### PR TITLE
[MDEP-849] Replace Maven shared StringUtils with Commons Lang3

### PR DESCRIPTION
**Pull request by timtebeek**
https://issues.apache.org/jira/browse/MNG-6825

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MDEP) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MDEP-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MDEP-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by timtebeek** [comment]
Apologies; this already had https://github.com/apache/maven-dependency-plugin/commit/69840a2002c209f6cb5983beae38deb0a58ddd52 applied but somehow that hadn't registered! I'll double check.

**Comment by timtebeek** [comment]
Still present in master branch: https://github.com/apache/maven-dependency-plugin/blob/master/src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java#L42

Yet somehow GitHub tells me there's conflicts with the master branch. 🤔

**Comment by slawekjaranowski** [comment]
@timtebeek Thanks for your work.

I prefer a separate issue for separate project. Each project is released independently and have own release notes.

**Comment by jira-importer** [comment]
Resolve #1353

**Pull request merged**
