### PR TITLE
[MDEP-717] Upgrade to 3.1.1 

### PR DESCRIPTION
**Pull request by elharo**
@ian-lavallee @rfscholte This upgrades the plugin to Maven 3.1 minimum with no org.sonatype classes.

### CODE REVIEW

**Comment by elharo** [comment]
There's a really nasty diamond dependency problem in the tree. We're pulling in asm:asm:3.3.1 and org.ow2.asm:asm:jar:8.0.1. You can see this in integration test failures.

**Comment by elharo** [comment]
Here's the problematic path:

[DEBUG] org.apache.maven.plugins:maven-dependency-plugin:jar:3.1.3-SNAPSHOT
[DEBUG]    org.apache.maven:maven-artifact:jar:3.1.0:compile
[DEBUG]    org.apache.maven:maven-plugin-api:jar:3.1.0:compile
[DEBUG]       org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.0.0.M2a:compile
[DEBUG]          javax.enterprise:cdi-api:jar:1.0:compile
[DEBUG]             javax.annotation:jsr250-api:jar:1.0:compile
[DEBUG]             javax.inject:javax.inject:jar:1:compile
[DEBUG]          com.google.guava:guava:jar:10.0.1:compile
[DEBUG]             com.google.code.findbugs:jsr305:jar:1.3.9:compile
[DEBUG]          org.sonatype.sisu:sisu-guice:jar:no_aop:3.1.0:compile
[DEBUG]             aopalliance:aopalliance:jar:1.0:compile
[DEBUG]          org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.0.0.M2a:compile
[DEBUG]             asm:asm:jar:3.3.1:compile

Can we exclude asm:asm or push the plugin api higher?

**Comment by elharo** [comment]
Excluding asm:asm causes a lot of this:

[ERROR] Errors: 
[ERROR]   TestCollectMojo.setUp:39->AbstractDependencyMojoTestCase.setUp:47->AbstractDependencyMojoTestCase.setUp:54->AbstractMojoTestCase.setUp:115->AbstractMojoTestCase.getContainer:261->AbstractMojoTestCase.setupContainer:227 » IncompatibleClassChange

**Comment by elharo** [comment]
Adding an extra dependency

```xml
    <dependency>
      <groupId>org.eclipse.sisu</groupId>
      <artifactId>org.eclipse.sisu.inject</artifactId>
      <version>0.0.0.M3</version>
    </dependency>
```

gets rid of asm:asm but causes lots of 


```
[ERROR]   TestClassifierTypeTranslator.setUp:63->AbstractDependencyMojoTestCase.setUp:47->AbstractDependencyMojoTestCase.setUp:54->AbstractMojoTestCase.setUp:115->AbstractMojoTestCase.getContainer:261->AbstractMojoTestCase.setupContainer:227 » NoClassDefFound
[ERROR]   TestClassifierTypeTranslator.setUp:63->AbstractDependencyMojoTestCase.setUp:47->AbstractDependencyMojoTestCase.setUp:54->AbstractMojoTestCase.setUp:115->AbstractMojoTestCase.getContainer:261->AbstractMojoTestCase.setupContainer:227 » NoClassDefFound
```

**Comment by elharo** [comment]
Going to 3.1.1 instead of 3.1.0 seems to work.

**Comment by slachiewicz** [comment]
Please check release note for 3.1.1 - there was one bug fixed to exclude a dependency

**Comment by elharo** [comment]
This passes. I wish I had tried this simple fix earlier. Any objections to making 3.1.1 the minimum?

**Comment by elharo** [comment]
This is probably a result of https://issues.apache.org/jira/browse/MNG-5499 which was fixed in 3.1.1

**Pull request merged**
