### PR TITLE
[MDEP-644] add resolver dependency

### PR DESCRIPTION
**Pull request by elharo**
@ian-lavallee let's see what this does to the ear test

### CODE REVIEW

**Comment by elharo** [comment]
org.elipse.aether.spi is in the resolver and in the aether dependency

[INFO] Running org.apache.maven.plugins.dependency.TestListClassesMojo
Exception in thread "pool-409-thread-1" java.lang.NoSuchMethodError: org.eclipse.aether.spi.connector.Transfer.setState(Lorg/eclipse/aether/spi/connector/Transfer$State;)Lorg/eclipse/aether/spi/connector/Transfer;
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)

**Comment by ian-lavallee** [comment]
@elharo CI still failing with the exclusion. I'll try excluding from the resolver next and then shading and ping you when I need a CI kicked off

**Comment by elharo** [comment]
The org.eclipse.aether.spi.connector.Transfer class does not have the setState method the wagon aether connector invokes.

Next step is to see if we can replace aether-connector-wagon with something more up to date.

**Comment by elharo** [comment]
[INFO] Running org.apache.maven.plugins.dependency.TestListClassesMojo
org.eclipse.aether.transfer.NoRepositoryConnectorException: No connector available to access repository central (https://repo.maven.apache.org/maven2) of type default using the available factories 
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:193)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:531)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:436)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:262)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:239)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:320)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:217)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:288)
	at org.apache.maven.shared.transfer.artifact.resolve.internal.Maven31ArtifactResolver.resolveArtifact(Maven31ArtifactResolver.java:104)
	at org.apache.maven.shared.transfer.artifact.resolve.internal.Maven31ArtifactResolver.resolveArtifact(Maven31ArtifactResolver.java:80)
	at org.apache.maven.shared.transfer.artifact.resolve.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:75)
	at org.apache.maven.plugins.dependency.ListClassesMojo.execute(ListClassesMojo.java:175)
	at org.apache.maven.plugins.dependency.TestListClassesMojo.testListClassesNotTransitive(TestListClassesMojo.java:74)

**Comment by michael-o** [comment]
Why does a test require outbound access?

**Comment by ian-lavallee** [comment]
I can't push to this branch because I don't have permissions but if you declare maven-resolver-transport-file, transport-http, api, util jetty-server and maven-compat it fixes the failing tests.

**Comment by jira-importer** [comment]
Resolve #1078

**Pull request closed without merging**
