### PR TITLE
[MDEP-613] - Fixes bug Analyze failed: Unsupported class file major version 55 (Java 11)

### PR DESCRIPTION
**Pull request by vbreivik**
Upgraded maven-dependency-analyzer to 1.11.0
This pulls in asm 7.0 supporting Java 11 and fixes MDEP-613: Analyze failed: Unsupported class file major version 55 (Java 11)

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MDEP-613) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MDEP-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MDEP-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by khmarbaise** [comment]
Just using the PR as it. Waiting for CI result see https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven-dependency-plugin/job/MDEP-613/

**Comment by khmarbaise** [comment]
Unfortunately being caught by MSHARED-786. Need to do a dependency-analyzer version 1.11.1 first.

**Comment by vbreivik** [comment]
I guess that did not go as well as I hoped. Glad the CI caught it.

**Comment by khmarbaise** [comment]
This was not related to the change you have made. It was an issue related having build [dependency-analyzer with JDK 9 which caused that issue](https://issues.apache.org/jira/browse/MSHARED-786).

**Comment by khmarbaise** [comment]
If we have released maven-dependency-analzyer 1.11.1 (you can vote on the DEV list) afterwards you can upgrade your PR and I appreciate to merge it....

**Comment by vbreivik** [comment]
I have tested the maven-dependency-analyzer 1.11.1 and voted on the dev list. I will try to follow up and update the PR when it 1.11.1 is released.

**Comment by vbreivik** [comment]
I bumped to maven-dependency-analyzer 1.11.1.

I just pushed another commit to the branch. I do not know if the norm is to amend the previous commit and force push to only have 1 commit, or if you want the history. Let me know if you want anything changed.

**Comment by khmarbaise** [comment]
Yeah great. Yes we do amend the previous to have only a single commit in the end...

**Comment by vbreivik** [comment]
> Yeah great. Yes we do amend the previous to have only a single commit in the end...

Good to know. I merged the commits and force pushed to the branch.

**Comment by khmarbaise** [comment]
Ok. Build your PR successfully. Thanks for your contribution.

**Comment by apolopeix** [comment]
When do you guys plan to have a new release that includes those changes? 
I see the changes in master, but the latest tag 3.1.1 does not include those changes.

**Comment by rfscholte** [comment]
@apolopeix [MDEP-613](https://issues.apache.org/jira/browse/MDEP-613) describes how you can fix this in your own pom, no need to wait for a release.

**Comment by apolopeix** [comment]
@rfscholte thanks, that was really helpful!

**Comment by jira-importer** [comment]
Resolve #1045

**Pull request closed without merging**
