### PR TITLE
[MDEP-940] Use Resolver API instead of m-a-t for resolving artifacts

### PR DESCRIPTION
**Pull request by slawekjaranowski**
https://issues.apache.org/jira/browse/MDEP-940

### CODE REVIEW

**Comment by michael-o** [comment]
MAT is still on the CP, no?

**Comment by slawekjaranowski** [comment]
> MAT is still on the CP, no?

Yes it is ... I do it step by step

**Comment by michael-o** [comment]
> > MAT is still on the CP, no?
> 
> Yes it is ... I do it step by step

Alright, let's convert to a draft.

**Comment by slawekjaranowski** [comment]
> > > MAT is still on the CP, no?
> > 
> > 
> > Yes it is ... I do it step by step
> 
> Alright, let's convert to a draft.

Why draft ... we can merge step by step with small changes.

**Comment by michael-o** [comment]
> > > > MAT is still on the CP, no?
> > > 
> > > 
> > > Yes it is ... I do it step by step
> > 
> > 
> > Alright, let's convert to a draft.
> 
> Why draft ... we can merge step by step with small changes.

I assumed that you wanted to work on a complete PR. If you think that PRs are seftcontained, that is fine. You decide.

**Comment by slawekjaranowski** [comment]
> > Why draft ... we can merge step by step with small changes.
> 
> I assumed that you wanted to work on a complete PR. If you think that PRs are seftcontained, that is fine. You decide.

Step by step ... other places is more complicated, eg use additional remote or local repository defined by user

**Pull request merged**
