### PR TITLE
MDEP-621 - New goal to "fix-warnings"

### PR DESCRIPTION
**Pull request by alexec**
The rational behind this PR is in the [MDEP-621 JIRA](https://issues.apache.org/jira/browse/MDEP-621) ticket. 

In summary, it adds a new goal that attemps to fix the warnings show by the `dependency:analyze` goal. This is so that large, but well-formed projects, can be automatically fixed.

THIS IS NOT READY FOR MERGE. 

I've opened this PR to allow for discussion and input around this feature.

---
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MDEP) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MDEP-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MDEP-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by alexec** [comment]
@rfscholte / @khmarbaise - as recent commiters, what do you think?

**Comment by khmarbaise** [comment]
The first thing which comes into my mind is: Where are tests? Either unit and/or integration tests for this ?

**Comment by alexec** [comment]
Good question! Naturally, it need unit tests and integration tests. I’ve written a couple of Maven plugins so I’m familiar with the process. 

But I don’t think this idea is there yet. I’m looking for fast feedback on the concept. Is this something that the plugin maintainers would want? If so, what advice can they give me? How would they like it done?

**Comment by alexec** [comment]
Closing due to lack of engagement.

**Comment by jira-importer** [comment]
Resolve #1054

**Pull request closed without merging**
