### PR TITLE
[MDEP-545] - Several classes create mixed-style line endings

### PR DESCRIPTION
**Pull request by ffaarno**
Replaced hard coded line endings in strings with System.lineSeperator.
As stated in the JIRA issue, I didn't touch the files under src/it.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MDEP) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MDEP-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MDEP-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by michael-o** [comment]
Will run ITs on Windows and FreeBSD...

**Comment by khmarbaise** [comment]
Ok @michael-o  you are faster.

**Comment by khmarbaise** [comment]
I will create a Branch on the project and run on ASF infrastructure....

**Comment by khmarbaise** [comment]
So lets see what CI says https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven-dependency-plugin/job/MDEP-545/

**Comment by michael-o** [comment]
@khmarbaise I have created the issue ;-)

**Comment by khmarbaise** [comment]
Ok Ok.. ;-) take the branch ;-)...

**Comment by sverhagen** [comment]
Not this ticket, but some of these use multiple calls to `getLog().info` to get their entire message across. It's a longer, multi-line message, but still a single message it's trying to convey, so ideally it should be one call to `getLog().info`, to hopefully keep things together in a multithreaded build?

**Comment by michael-o** [comment]
@sverhagen feel free to open a new ticket pointing to those spots!

**Pull request closed without merging**
