### PR TITLE
[MDEP-626] Upgrade maven-reporting-impl

### PR DESCRIPTION
**Pull request by mthmulders**
This newer version doesn't depend on struts2-core or xercesImpl.

Following this checklist to help us incorporate your contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MDEP) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MDEP-XXX] - Fixes bug in ApproximateQuantiles`, where you replace `MDEP-XXX` with the appropriate JIRA issue. Best practice is to use the JIRA issue title in the pull request title and in the first line of the  commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [X] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure please ask on the developers list.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by mthmulders** [comment]
I have generated the site using the old version (2.3) and the new version (3.0.0). A recursive diff is [attached](https://github.com/apache/maven-dependency-plugin/files/3697076/site-diff.txt).

What I can see is that some of the content changed (since this newer version pulls in other dependencies). And links to external addresses have an additional CSS class "externalLink" - I don't think that should be a big problem?

**Comment by khmarbaise** [comment]
I don't expect any issue but lets see what CI says https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven-dependency-plugin/job/mthmulders-MDEP-626-mthmulders/

**Comment by khmarbaise** [comment]
Unfortunately there is an integration test which has failed....I think there is something to do ;-)

**Comment by mthmulders** [comment]
That's right! I've upgraded Doxia and added the doxia-core module. Integration tests succeeded on my machine.

**Comment by khmarbaise** [comment]
Ok pulled the changed and pushed to the branch so lets take break and see what CI says now https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven-dependency-plugin/job/mthmulders-MDEP-626-mthmulders/

**Comment by khmarbaise** [comment]
So rebased and squashed the commits into a single one...waiting for CI afterwards I will merge them into master. Thanks for your contribution.

**Comment by khmarbaise** [comment]
So I have merged your PR to master and close the appropriate jira issue as well. Many thanks for your contribution.

**Comment by mthmulders** [comment]
You're welcome, happy to be able to contribute :-)

**Comment by jira-importer** [comment]
Resolve #1061

**Pull request closed without merging**
