### PR TITLE
timestamp for new release

### PR DESCRIPTION
**Pull request by elharo**
@hboutemy

### CODE REVIEW

**Review by michael-o — COMMENTED** [review]
Why did you change this? Maven Release Plugin will do this automatically.

**Comment by elharo** [comment]
Because the (possibly out of date and incorrect) Apache instructions for "Publishing Maven Releases to Maven Central Repository" say to:


  Diff the original file pom.xml with the one called pom.xml.tag to see if the license or any other info   has been removed. This has been known to happen if the starting <project> tag is not on a single line. The only things that should be different between these files are the <version> and <scm> elements. Backport any other changes you find to the original pom.xml file and commit it before proceeding with the release.

**Comment by michael-o** [comment]
That's confusing. We have never done this. Updating this property shall not be necessary manually. @hboutemy has taken care of this.

**Comment by elharo** [comment]
It would help if someone could update https://infra.apache.org/publishing-maven-artifacts.html
I do not seem to have permissions to do this. This is not the only incorrect instruction on that page.

**Pull request closed without merging**
