### PR TITLE
[MDEP-568] fix APIs method names and other requests from elharo in #135

### PR DESCRIPTION
**Pull request by antoniolucasnobar**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MDEP) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MDEP-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MDEP-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by slachiewicz** [comment]
Please rebase on master

**Comment by pzygielo** [comment]
> Please rebase on master

Not sure how this would help, as this PR aims to merge all 100+ commits present in master to `MDEP-568_go-offline_filter` branch that is waaay behind master.

I think that 3a06622 (merge master) should rather be dropped. It would leave this PR with only ~6 new commits to target base branch.

**Comment by antoniolucasnobar** [comment]
@slachiewicz do you really want me to do a rebase? After what @pzygielo said?

@pzygielo do you want me to create two PRs? one only with my commits and one with merge with master? Is that it?

In the merge I had to resolve simple conflicts in one file.

Thanks in advance for your help and guidance.

**Comment by antoniolucasnobar** [comment]
I rebased my branch with master. But I still can not reopen this PR.

**Comment by jira-importer** [comment]
Resolve #1004

**Pull request closed without merging**
