### PR TITLE
[MDEP-900] dependency:resolve fails for multi-module project

### PR DESCRIPTION
**Pull request by michael-o**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MDEP) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MDEP-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MDEP-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by michael-o** [comment]
This one lacks a test...

**Comment by michael-o** [comment]
@slawekjaranowski Can we use the IT from https://github.com/apache/maven-dependency-plugin/pull/349?

**Comment by slawekjaranowski** [comment]
ups existing tests failed ...

**Comment by michael-o** [comment]
> ups existing tests failed ...

I am running locally, will report...

**Comment by michael-o** [comment]
I have the reason and the reason is valid and I believe that 0bb4c5917222c4f4a6df53bbc70dd770507a3d4d must be reverted.
The goal is called `resolve`, the other one should have been called `resolve-sources`. The source code clearly says:
```
            // dependencies:collect won't download jars
            if (artifact.getFile() != null) {
                ModuleDescriptor moduleDescriptor = getModuleDescriptor(artifact.getFile());
                if (moduleDescriptor != null) {
                    messageBuilder.project(" -- module " + moduleDescriptor.name);

                    if (moduleDescriptor.automatic) {
                        if ("MANIFEST".equals(moduleDescriptor.moduleNameSource)) {
                            messageBuilder.strong(" [auto]");
                        } else {
                            messageBuilder.warning(" (auto)");
                        }
                    }
                }
            }
```
So we need `collect-sources` maybe as well. I am inclined to close MDEP-900 as wontfix and revert MDEP-895.

**Comment by slawekjaranowski** [comment]
> ...
> So we need `collect-sources` maybe as well. I am inclined to close [MDEP-900](https://issues.apache.org/jira/browse/MDEP-900) as wontfix and revert [MDEP-895](https://issues.apache.org/jira/browse/MDEP-895).

@michael-o I checked again .... you are right here ... if we have a resolve-xxx mojo dependencies should be resolved

There can be a bug in maven-artifact-transfer ... during build list of dependenies
I working step by step to get rid of ot

**Comment by michael-o** [comment]
> > ...
> > So we need `collect-sources` maybe as well. I am inclined to close [MDEP-900](https://issues.apache.org/jira/browse/MDEP-900) as wontfix and revert [MDEP-895](https://issues.apache.org/jira/browse/MDEP-895).
> 
> @michael-o I checked again .... you are right here ... if we have a resolve-xxx mojo dependencies should be resolved
> 
> There can be a bug in maven-artifact-transfer ... during build list of dependenies I working step by step to get rid of ot

I'd say the first we should revert [MDEP-895](https://issues.apache.org/jira/browse/MDEP-895) and the have a look at your idea. Both tickets should remain open for the time being.

**Comment by michael-o** [comment]
Revert is here: #408

**Comment by michael-o** [comment]
Closing this experiment, leaving the branch.

**Comment by jira-importer** [comment]
Resolve #1409

**Pull request closed without merging**
