### PR TITLE
[MDEP-894] Use `@Component` only - fix tests

### PR DESCRIPTION
**Pull request by michael-o**
This should depict the failing behavior.

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
Unit tests still fail for me .... 
But executing ITs are ok ...

**Comment by michael-o** [comment]
> Unit tests still fail for me .... But executing ITs are ok ...

Yes, that's the point. A misconfig or dep is missing.

**Comment by slawekjaranowski** [comment]
@michael-o @cstamas please look at my commit ... I fix one test by adding mock MavenProject and MavenSession as component in test

**Comment by slawekjaranowski** [comment]
Unit test pass.

Site build due to parameters list can be null 😄

**Comment by michael-o** [comment]
@slawekjaranowski This is fantastic work, **thank you**. Your change must go with the upgrade of MPLUGIN with every modified plugin as well as this one.

**Comment by slawekjaranowski** [comment]
rebased and use latest released versions of m-plugin-tools

**Review by slawekjaranowski — APPROVED** [review]

**Pull request merged**
